accounts/urls.py
from django.urls import path
from .views import edit, dashboard, register
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordResetDoneView,
                                       PasswordResetView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetDoneView)

app_name = 'accounts'

urlpatterns = [
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('logout/',
         LogoutView.as_view(template_name='accounts/logged_out.html'),
         name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='accounts/password_change_form.html'),
         name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html',
        success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('accounts:login')),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.conf import settings


class UserRegistrationModel(models.Model):
    """
    Містить OneToOneField() з інформацією,
    що стосується конкретного користувача.
    """
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        verbose_name='Користувач')

accounts/forms.py
""" Відповідає за створення, обробку та налаштування форм. """
# !/usr/bin/env python3
# -*- coding=utf-8 -*-

from django import forms
from django.contrib.auth.models import User


# from .models import Profile


class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

        def clean_password2(self):
            """
            Користувацький метод перевірки,
            який просто гарантує, що обидва паролі збігаються,
            інакше це спричинить помилку перевірки.
            """
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

accounts/views.py
from django.http import request
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserRegistration, UserEditForm


# @login_required - робить функцію доступною лише для користувача,
# що увійшов у систему.
@login_required
def dashboard(request):
    """
    Показує користувачеві текст
    «Ласкаво просимо до вашої інформаційної панелі».
    """
    context = {
        "welcome": "Welcome to your dashboard"
    }
    return render(request, 'accounts/dashboard.html', context=context)


def register(request):
    """
    Відповідає за реєстрацію нового користувача.
    """
    if request.method == 'POST':
        form = UserRegistration(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            # хешування нового пароля користувача
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'accounts/register_done.html')
    else:
        form = UserRegistration()

    context = {
        "form": form
    }

    return render(request, 'accounts/register.html', context=context)


@login_required
def edit(request):
    """
    Функція дає користувачеві можливість редагувати поля.
    """
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
    context = {
        'form': user_form,
    }
    return render(request, 'accounts/edit.html', context=context)

accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
    {# містить повідомлення {{welcome}} з функції інформаційної панелі у файлі views.py. #}
    <h1>{{ welcome }}</h1>
    <br>
    <a href="{% url 'accounts:edit' %}" class="btn btn-primary">
        Edit Your Profile
    </a> or
    <a href="{% url 'accounts:password_change' %}" class="btn btn-warning">
        Change your password
    </a>
    <hr>
{% endblock content %}

accounts/templates/accounts/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}Edit{% endblock title %}

{% block content %}
    <h2>Edit your account</h2>
    <p>You can edit your account using the follow form</p>

    <form action="" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>

{% endblock content %}

accounts/templates/accounts/logged_out.html
{% extends "base.html" %}

{% block title %}Logged out{% endblock %}

{% block content %}
    <h1>Logged out</h1>
    <p>
        You have been successfully logged out.
        <hr>
        You can <a href="{% url 'accounts:login' %}">log-in again</a>.
    </p>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}Login{% endblock title %}

{% block content %}
    <div class="">
        <div style="text-align: center;">
            <h1>Log-in</h1>
            {% if form.errors %}
                <p>
                    Your username and password didn't match.Please
                    Please try again.
                </p>
            {% else %}
                <p>Please, use the following form to log-in</p>
            {% endif %}
        </div>

        <form action="" method="post" class="form ">
            <p>
                <a href="{% url 'accounts:password_reset' %}">
                    Forgotten your password?
                </a>
            </p>

            {% csrf_token %}
            {% bootstrap_form form %}

            {% buttons %}
                <input type="hidden" name="next" value="{{ next }}" />
                <button type="submit" class="btn btn-primary">Submit</button>
            {% endbuttons %}
        </form>
    </div>
{% endblock content %}

accounts/templates/accounts/password_change_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <h2>Change Your Password</h2>
    <p>Use the form below to change your Password</p>

    <form action="" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>

{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Password reset{% endblock %}

{% block content %}
    <h2>Password set</h2>
    <p>Your password has been set. You can
        <a href="{% url 'accounts:login' %}">
            log in now
        </a>
    </p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <h1>Reset your password</h1>

    {% if validlink %}
        <p>Please enter your new password twice:</p>

        <form action="" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary" value="Change my password">Submit</button>
            {% endbuttons %}
        </form>
    {% else %}
        <p>The password reset link was invalid, possibly because it has
            already been used. Please request a new password reset.</p>
    {% endif %}

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <h1>Reset your password</h1>
    <p>We've emailed you instructions for setting your password.</p>
    <p>If you don't receive an email, please make sure you've entered
        the address you registered with.</p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{email}}.Follow the Link below
{{ protocol }}://{{ domain }}{% url "accounts:password_reset_confirm"
uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Reset your password{% endblock title %}

{% block content %}
    <div class="container">
        <h2>Forgotten your Password</h2>
        <p>Enter your email address to obtain a new password</p>

        <form action="" method="post" class="form ">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary" value="send e-mail">Submit</button>
            {% endbuttons %}
        </form>

    </div>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}Registration{% endblock title %}

{% block content %}

{% if form.errors %}
    
{% endif %}
    
<form action="" method="post" class="form container">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock content %}

accounts/templates/accounts/register_done.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>
    <p>Your account has been successfully created.
        Now you can <a href="{% url 'accounts:login' %}">log in</a>.
    </p>
{% endblock content %}

accounts/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

        <!-- Font Awesome CDN -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
            integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">

        <title>App {% block title %}{% endblock title %}</title>
    </head>

    <body>

        {% include "accounts/include/_navbar.html" %}

        <div class="container">
            {% block content %}

            {% endblock content %}
        </div>



        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    </body>
</html>